server:
  port: ${REST_SERVER_PORT:3001}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: sample-graphql
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/db_employee}
    username: ${MYSQL_USER_NAME:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
  output:
    ansi:
      enabled: always
  graphql:
    graphiql:
      enabled: true
#grpc
grpc:
  server:
    port: ${GRPC_SERVER_PORT:3101}