server:
  port: ${REST_SERVER_PORT:3003}

spring:
  profiles:
    active: ${ACTIVE_PROFILE:local}
  application:
    name: sample-rabbitmq
  output:
    ansi:
      enabled: always
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    port: ${RABBITMQ_PORT:5672}