#management
management:
  #tracing
  tracing:
    enabled: ${ENABLED_TRACING:false}
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${ZIPKIN_SERVER:http://localhost:9411/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: prometheus, metrics, info, health, beans
  endpoint:
    health:
      show-details: never
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
#logging
logging:
  loki:
    enpoint: ${LOKI_SERVER:http://localhost:3100/loki/api/v1/push}