apiVersion: v1
kind: Service
metadata:
  name: local-service-uaa
spec:
  type: ClusterIP
  selector:
    component: service-uaa-pod
  ports:
    - port: 8080
      protocol: TCP
      name: rest-port
      targetPort: 8080
    - port: 8085
      protocol: TCP
      name: grpc-port
      targetPort: 8085

---
# envoy proxy
apiVersion: v1
kind: Service
metadata:
  name: service-uaa
spec:
  type: ClusterIP
  selector:
    app: uaa-envoy-proxy-pod
  ports:
    # Service only exposes the Envoy container
    - name: envoy-port
      protocol: TCP
      port: 8080
      targetPort: envoy-port